version: '2'

services:
  server:
    restart: unless-stopped
    build:
      context: ./packages/server
      dockerfile: ./Dockerfile-development
    depends_on:
      - db
    entrypoint:
      [
        'sh',
        'scripts/wait-for-it',
        'db:5432',
        '--',
        'sh',
        'scripts/setupDevServer.sh'
      ]
    command:
      [
        'node_modules/.bin/nodemon',
        'startServer.js',
        '--',
        'config',
        '--',
        'api',
        '--',
        'models',
        '--',
        'scripts',
        '--',
        'startServer.js',
        '--',
        'app.js',
        '--ext',
        'js,graphql'
      ]
    ports:
      - ${SERVER_PORT:-4000}:${SERVER_PORT:-4000}
    environment:
      - NODE_ENV=development
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-dev_secret}
      - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL:-http://server:4000}
      - SERVER_SERVE_CLIENT=false
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-cokodocs_dev}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_user_password}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - ADMIN_GIVEN_NAME=${ADMIN_GIVEN_NAME:-Admin}
      - ADMIN_SURNAME=${ADMIN_SURNAME:-Adminius}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - SERVER_PORT=${SERVER_PORT:-4000}
      - SERVER_HOST=${SERVER_HOST:-localhost}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL:-http}
      - CLIENT_PROTOCOL=${CLIENT_PROTOCOL:-http}
      - CLIENT_HOST=${CLIENT_HOST:-0.0.0.0}
      - CLIENT_PORT=${CLIENT_PORT:-3000}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SENDER=${MAILER_SENDER:-dev@example.com}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH:-password-reset}
      - USE_WEBSOCKET=${USE_WEBSOCKET:-true}
      - WEB_SOCKET_PATH=${WEB_SOCKET_PATH:-yjs}
    volumes:
      - ./packages/server/config:/home/node/cokodocs/config
      - ./packages/server/api:/home/node/cokodocs/api
      - ./packages/server/models:/home/node/cokodocs/models
      - ./packages/server/scripts:/home/node/cokodocs/scripts
      - ./packages/server/app.js:/home/node/cokodocs/app.js
      - ./packages/server/startServer.js:/home/node/cokodocs/startServer.js
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-cokodocs_dev}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_user_password}
    volumes:
      - ./scripts/init-pgboss.sql:/docker-entrypoint-initdb.d/init-pgboss.sql
