version: '2'

services:
  server:
    restart: unless-stopped
    build:
      context: ./packages/server
      dockerfile: ./Dockerfile-production
    ports:
      - ${SERVER_PORT:-4000}:${SERVER_PORT:-4000}
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
